# Default values for cert-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-values
  namespace: cert-manager
data:
  values.yaml: |
    replicaCount: 2
